kind: pipeline
name: default

steps: 
- name: publish_docker
  image: plugins/docker
  settings:
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
    repo: prakashshettigar23/networkapp
    dockerfile : /drone/src/DockerFile
    context: /drone/src
    tags:
      - latest
      - cnm-0.1-SNAPSHOT-${DRONE_BUILD_NUMBER}

- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token