# Generated by Django 2.1.5 on 2019-02-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCredentialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.CharField(max_length=15)),
                ('device_username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
