# Generated by Django 2.1.5 on 2019-02-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0007_auto_20190224_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
